---
- name: add grafana packaging key
  apt_key: url=https://packages.grafana.com/gpg.key
- name: add grafana deb repository
  apt_repository: repo='deb https://packages.grafana.com/oss/deb stable main'
  register: add_apt_repo
- name: update APT cache
  apt: update_cache=yes
  when: add_apt_repo.changed
- name: install grafana
  apt:
    state: present
    name:
    - grafana
  notify:
    - restart grafana-server
- name: configure grafana
  template: dest=/etc/grafana/grafana.ini src=templates/grafana.ini group=grafana mode=0640
  notify:
    - restart grafana-server
- include_role: name=nginx-site
  vars:
    nginx_conf: "nginx.conf"
- name: add www-data to grafana group
  user: name=www-data groups=grafana append=yes
  notify:
    - restart nginx
- import_tasks: influxdb.yml
  when: influxdb
