- name: install git
  apt: name=git state=present
- name: create webroot for groupxiv.whitequark.org
  file: dest=/var/www/groupxiv.whitequark.org state=directory owner=whitequark
- name: deploy groupxiv.whitequark.org
  git: dest=/var/www/groupxiv.whitequark.org repo=https://github.com/whitequark/groupxiv
    accept_hostkey=yes
  become: true
  become_user: whitequark
- include_tasks: tasks/nginx-site.yml name=groupxiv.whitequark.org
