---
- hosts: uruz.whitequark.org
  vars:
    live: yes
    want_tls: yes
  vars_files:
  - vars/private.yml
  - vars/public.yml
  pre_tasks:
  - include: tasks/system.yml
    tags: system
  - include: tasks/personal.yml
    tags: personal
  - include: tasks/nsd.yml
    tags: nsd
  - include: tasks/nsd-zone.yml name=whitequark.org
    tags: nsd, nsd:whitequark.org
  - include: tasks/nsd-zone.yml name=llvm.moe
    tags: nsd, nsd:llvm.moe
  - include: tasks/mail.yml domain=mail.whitequark.org
    tags: mail
  # - include: tasks/nginx.yml
  #   tags: nginx
  # - include: tasks/nginx-site.yml name=uruz.whitequark.org
  #   tags: uruz.whitequark.org
  - include: tasks/roundcube.yml domain=mail.whitequark.org
    tags: mail.whitequark.org
  # - include: tasks/prestashop.yml domain=shop.whitequark.org version=1.7.2.2
  #   tags: shop.whitequark.org
  # - include: tasks/sites/www.whitequark.org.yml
  #   tags: www.whitequark.org
  # - include: tasks/sites/files.whitequark.org.yml
  #   tags: files.whitequark.org
  # - include: tasks/sites/lab.whitequark.org.yml
  #   tags: lab.whitequark.org
  # - include: tasks/sites/groupxiv.whitequark.org.yml
  #   tags: groupxiv.whitequark.org
  - include: tasks/nginx-site.yml name=mail.whitequark.org
    tags: mail.whitequark.org, mail.whitequark.org:nginx
  # - include: tasks/nginx-site.yml name=shop.whitequark.org
  #   tags: shop.whitequark.org, shop.whitequark.org:nginx
  - include: tasks/sites/whitequark.org.yml
    tags: whitequark.org
  # - include: tasks/nginx-site.yml name=whitequark.com
  #   tags: whitequark.com
  # - include: tasks/sites/llvm.moe.yml
  #   tags: llvm.moe
  - include: tasks/mumble.yml
    tags: mumble
  # - include: tasks/tarsnap.yml
  #   tags: tarsnap
  # - include: tasks/backup.yml
  #   tags: backup
  roles:
  # tasks/system.yml
  # tasks/personal.yml
  # tasks/mumble.yml
  # tasks/nsd.yml
  # tasks/mail.yml domain=mail.whitequark.org
  - name: nginx
  - name: nginx-site # default server
    domain: uruz.whitequark.org
    tags:   uruz.whitequark.org
  #   >>> whitequark.com <<<
  - name: nginx-site
    domain: whitequark.com
    tags:   whitequark.com
  #   >>> whitequark.org <<<
  # tasks/nsd-zone.yml name=whitequark.org
  - name: nginx-site
    domain: whitequark.org
    tags:   whitequark.org
  - name: nginx-site
    domain: www.whitequark.org
    tags:   www.whitequark.org
  - name: nginx-site
    domain: files.whitequark.org
    tags:   files.whitequark.org
  - name: nginx-site
    domain: lab.whitequark.org
    tags:   lab.whitequark.org
  - name: nginx-site
    domain: groupxiv.whitequark.org
    tags:   groupxiv.whitequark.org
  - name: irclogger
    network: freenode
    domain:  freenode.irclog.whitequark.org
    tags:    freenode.irclog.whitequark.org
  - name: nginx-site
    domain: irclog.whitequark.org
    tags:   irclog.whitequark.org
  - name: nginx-site
    domain: logs.jruby.org
    tags:   logs.jruby.org
  - name: irclogger
    network: esper
    domain:  esper.irclog.whitequark.org
    tags:    esper.irclog.whitequark.org
  # tasks/roundcube.yml domain=mail.whitequark.org
  # tasks/nginx-site.yml name=mail.whitequark.org
  - name: prestashop
    domain: shop.whitequark.org
  - name: nextcloud
    domain: cloud.whitequark.org
    tags:   cloud.whitequark.org
  - name: notifico
    domain: notifico.whitequark.org
    tags:   notifico.whitequark.org
  - name: nginx-site
    domain: gateway.whitequark.org
    tags:   gateway.whitequark.org
  - name: flarum
    domain: glasgow.whitequark.org
    webroot:  /var/www/glasgow.whitequark.org
    instance: glasgow
    tags:   glasgow.whitequark.org
  - name: influxdb
    domain: influxdb.whitequark.org
    tags:   influxdb.whitequark.org
  #   >>> llvm.moe <<<
  # tasks/nsd-zone.yml name=llvm.moe
  - name: nginx-site
    domain: llvm.moe
    tags:   llvm.moe
  - name: tarsnap
    tags: backup
  handlers:
  - include: handlers/sysctl.yml
  - include: handlers/syslog.yml
  - include: handlers/nsd.yml
  - include: handlers/mail.yml
  - include: handlers/mysql.yml
  - include: handlers/roundcube.yml
  - include: handlers/mumble.yml
