---
- hosts: uruz.whitequark.org
  vars:
    live: yes
    want_tls: yes
  vars_files:
  - vars/private.yml
  - vars/public.yml
  pre_tasks:
  - import_tasks: tasks/system.yml
    tags: system
  - import_tasks: tasks/nsd.yml
    tags: nsd
  - import_tasks: tasks/nsd-zone.yml
    vars:
      zone: whitequark.org
    tags: nsd, nsd:whitequark.org
  roles:
  - name: nginx
  - name: nginx-site # default server
    domain: uruz.whitequark.org
    tags:   uruz.whitequark.org
  #   >>> whitequark.org <<<
  - name: nextcloud
    domain: cloud.whitequark.org
    tags:   cloud.whitequark.org
  - name: tarsnap
    tags: backup
  handlers:
  - import_tasks: handlers/sysctl.yml
  - import_tasks: handlers/syslog.yml
  - import_tasks: handlers/nsd.yml
  - import_tasks: handlers/mysql.yml
