---
- hosts: uruz.whitequark.org
  vars:
    live: yes
    want_tls: yes
  vars_files:
  - vars/private.yml
  - vars/public.yml
  pre_tasks:
  - include: tasks/system.yml
    tags: system
  - include: tasks/personal.yml
    tags: personal
  - include: tasks/nsd.yml
    tags: nsd
  - include: tasks/nsd-zone.yml name=whitequark.org
    tags: nsd, nsd:whitequark.org
  - include: tasks/nsd-zone.yml name=llvm.moe
    tags: nsd, nsd:llvm.moe
  - include: tasks/mail.yml domain=mail.whitequark.org
    tags: mail
  - include: tasks/roundcube.yml domain=mail.whitequark.org
    tags: mail.whitequark.org
  - include: tasks/nginx-site.yml name=mail.whitequark.org
    tags: mail.whitequark.org, mail.whitequark.org:nginx
  - include: tasks/sites/whitequark.org.yml
    tags: whitequark.org
  - include: tasks/mumble.yml
    tags: mumble
  roles:
  - name: nginx
  - name: nginx-site # default server
    domain: uruz.whitequark.org
    tags:   uruz.whitequark.org
  #   >>> whitequark.com <<<
  - name: nginx-site
    domain: whitequark.com
    tags:   whitequark.com
  #   >>> whitequark.org <<<
  - name: nginx-site
    domain: whitequark.org
    tags:   whitequark.org
  - name: nginx-site
    domain: www.whitequark.org
    tags:   www.whitequark.org
  - name: nginx-site
    domain: files.whitequark.org
    tags:   files.whitequark.org
  - name: nginx-site
    domain: lab.whitequark.org
    tags:   lab.whitequark.org
  - name: nginx-site
    domain: groupxiv.whitequark.org
    tags:   groupxiv.whitequark.org
  - name: irclogger
    network: freenode
    domain:  freenode.irclog.whitequark.org
    tags:    freenode.irclog.whitequark.org
  - name: irclogger
    network: libera
    domain:  libera.irclog.whitequark.org
    tags:    libera.irclog.whitequark.org
  - name: irclogger
    network: oftc
    domain:  oftc.irclog.whitequark.org
    tags:    oftc.irclog.whitequark.org
  - name: nginx-site
    domain: irclog.whitequark.org
    tags:   irclog.whitequark.org
  - name: nginx-site
    domain: logs.jruby.org
    tags:   logs.jruby.org
  - name: irclogger
    network: esper
    domain:  esper.irclog.whitequark.org
    tags:    esper.irclog.whitequark.org
  - name: nextcloud
    domain: cloud.whitequark.org
    tags:   cloud.whitequark.org
  - name: notifico
    domain: notifico.whitequark.org
    tags:   notifico.whitequark.org
  - name: nginx-site
    domain: gateway.whitequark.org
    tags:   gateway.whitequark.org
  - name: flarum
    domain: glasgow.whitequark.org
    webroot:  /var/www/glasgow.whitequark.org
    instance: glasgow
    tags:   glasgow.whitequark.org
  - name: influxdb
    domain: influxdb.whitequark.org
    tags:   influxdb.whitequark.org
  - name: grafana
    domain: grafana.whitequark.org
    tags:   grafana.whitequark.org
    influxdb: yes
  - name: dendrite
    version: v0.3.11
    server: whitequark.org
    domain: matrix.whitequark.org
    tags:   matrix.whitequark.org
  #   >>> llvm.moe <<<
  - name: nginx-site
    domain: llvm.moe
    tags:   llvm.moe
  - name: tarsnap
    tags: backup
  tasks:
  - include: tasks/sensors.yml
    tags: sensors
  handlers:
  - include: handlers/sysctl.yml
  - include: handlers/syslog.yml
  - include: handlers/nsd.yml
  - include: handlers/mail.yml
  - include: handlers/mysql.yml
  - include: handlers/roundcube.yml
  - include: handlers/mumble.yml
