---
- hosts: uruz.whitequark.org
  vars:
    live: yes
    want_tls: yes
  vars_files:
  - vars/private.yml
  - vars/public.yml
  pre_tasks:
  - include_tasks: tasks/system.yml
    tags: system
  - include_tasks: tasks/personal.yml
    tags: personal
  - import_tasks: tasks/nsd.yml
    tags: nsd
  - import_tasks: tasks/nsd-zone.yml
    vars:
      zone: whitequark.org
    tags: nsd, nsd:whitequark.org
  - import_tasks: tasks/nsd-zone.yml
    vars:
      zone: llvm.moe
    tags: nsd, nsd:llvm.moe
  - include_tasks: tasks/mail.yml
    vars:
      domain: mail.whitequark.org
    tags: mail
  - include_tasks: tasks/roundcube.yml
    vars:
      domain: mail.whitequark.org
    tags: mail.whitequark.org
  - include_tasks: tasks/nginx-site.yml
    vars:
      name: mail.whitequark.org
    tags: mail.whitequark.org, mail.whitequark.org:nginx
  - include_tasks: tasks/sites/whitequark.org.yml
    tags: whitequark.org
  - include_tasks: tasks/mumble.yml
    tags: mumble
  roles:
  - name: nginx
  - name: nginx-site # default server
    domain: uruz.whitequark.org
    tags:   uruz.whitequark.org
  #   >>> whitequark.com <<<
  - name: nginx-site
    domain: whitequark.com
    tags:   whitequark.com
  #   >>> whitequark.org <<<
  - name: nginx-site
    domain: whitequark.org
    tags:   whitequark.org
  - name: nginx-site
    domain: www.whitequark.org
    tags:   www.whitequark.org
  - name: nginx-site
    domain: files.whitequark.org
    tags:   files.whitequark.org
  - name: nginx-site
    domain: lab.whitequark.org
    tags:   lab.whitequark.org
  - name: nginx-site
    domain: groupxiv.whitequark.org
    tags:   groupxiv.whitequark.org
  - name: nginx-site
    domain: libera.irclog.whitequark.org
    tags:   libera.irclog.whitequark.org, irclog.whitequark.org
  - name: nginx-site
    domain: oftc.irclog.whitequark.org
    tags:   oftc.irclog.whitequark.org, irclog.whitequark.org
  - name: nginx-site
    domain: esper.irclog.whitequark.org
    tags:   esper.irclog.whitequark.org, irclog.whitequark.org
  - name: nginx-site
    domain: freenode.irclog.whitequark.org
    tags:   freenode.irclog.whitequark.org, irclog.whitequark.org
  - name: nginx-site # alias for libera.irclog.whitequark.org/jruby
    domain: logs.jruby.org
    tags:   logs.jruby.org, irclog.whitequark.org
  - name: nginx-site # legacy alias for freenode.irclog.whitequark.org
    domain: irclog.whitequark.org
    tags:   freenode.irclog.whitequark.org, irclog.whitequark.org
  - name: nextcloud
    domain: cloud.whitequark.org
    tags:   cloud.whitequark.org
  - name: notifico
    domain: notifico.whitequark.org
    tags:   notifico.whitequark.org
  - name: nginx-site
    domain: gateway.whitequark.org
    tags:   gateway.whitequark.org
  #   >>> llvm.moe <<<
  - name: nginx-site
    domain: llvm.moe
    tags:   llvm.moe
  - name: tarsnap
    tags: backup
  handlers:
  - include_tasks: handlers/sysctl.yml
  - include_tasks: handlers/syslog.yml
  - import_tasks: handlers/nsd.yml
  - include_tasks: handlers/mail.yml
  - include_tasks: handlers/mysql.yml
  - include_tasks: handlers/roundcube.yml
  - include_tasks: handlers/mumble.yml
