#!/bin/sh
# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi
### BEGIN INIT INFO
# Provides:          photobackup
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: photo backup service
### END INIT INFO

# Author: whitequark <whitequark@whitequark.org>

START_ARGS="--chuid whitequark -d /home/whitequark -m -b"

DESC="photobackup"
DAEMON=/usr/bin/python3
DAEMON_ARGS="/usr/local/bin/photobackup run"
