---
# FIXME: evaluate this!
# - name: add nextcloud binary packaging key
#   apt_key: url=http://apt.jurisic.org/Release.key
# - name: add nextcloud deb repository
#   apt_repository: repo='deb http://apt.jurisic.org/debian/ stretch main non-free'
#   register: add_apt_repo
# - name: update APT cache
#   apt: update_cache=yes
#   when: add_apt_repo.changed
- name: install nextcloud, mysql, php, php extensions, and spawn-fcgi
  apt: name={{item}} state=present
  with_items:
  - python-mysqldb # for ansible
  - default-mysql-server
  - php-gd
  - php-json
  - php-mysql
  - php-curl
  - php-intl
  - php-mcrypt
  - php-imagick
  - php-zip
  - php-xml
  - php-mbstring
  - php-apcu
  - spawn-fcgi
  notify:
  - restart nextcloud
- name: create user nextcloud
  user: name=nextcloud shell=/usr/sbin/nologin
- name: configure mysql for nextcloud
  file: dest=/etc/mysql/conf.d/nextcloud.cnf src=mysqld.cnf
  notify:
  - restart mysql
- name: create mysql database nextcloud
  mysql_db: name=nextcloud state=present
- name: create mysql database user nextcloud
  mysql_user: name=nextcloud state=present priv=nextcloud.*:ALL
- name: create webroot for nextcloud
  file: dest={{webroot}} state=directory owner=nextcloud
- name: add nextcloud init script
  copy: dest=/etc/init.d/nextcloud src=rc.sh mode=0755
  notify:
  - restart nextcloud
- name: enable nextcloud service
  service: name=nextcloud state=started enabled=yes
- name: configure nextcloud system cron
  cron: name="nextcloud" minute="*/15" job="/usr/bin/php -f {{webroot}}/cron.php"
  become: true
  become_user: nextcloud
