apiVersion: 1

datasources:
  - name: "Sensors"
    type: influxdb
    url: http://localhost:8086
    access: proxy
    user: grafana
    database: sensors
    editable: false
    jsonData:
      httpMode: POST
    secureJsonData:
      password: {{influxdb_password.grafana}}
