---
- name: install mysql, php, php extensions, spawn-fcgi, and composer
  apt:
    state: present
    name:
    - python-mysqldb # for ansible
    - default-mysql-server
    - php7.3-cgi
    - php7.3-curl
    - php7.3-dom
    - php7.3-gd
    - php7.3-json
    - php7.3-mbstring
    # - php7.3-openssl
    - php7.3-pdo
    - php7.3-tokenizer
    - php7.3-zip
    - spawn-fcgi
    - composer
  notify:
  - restart flarum
- name: create user flarum-{{instance}}
  user: name=flarum-{{instance}} shell=/usr/sbin/nologin
- name: create mysql database flarum-{{instance}}
  mysql_db: name=flarum-{{instance}} state=present
- name: create mysql database user flarum-{{instance}}
  mysql_user: name=flarum-{{instance}} state=present priv=flarum-{{instance}}.*:ALL
- name: create webroot for flarum
  file: dest={{webroot}} state=directory owner=flarum-{{instance}}
- name: check if flarum is already installed
  stat: path={{webroot}}/flarum
  register: flarum
- name: install flarum
  command: composer create-project flarum/flarum {{webroot}} --stability=beta
  become: true
  become_user: "flarum-{{instance}}"
  register: app_install
  when: not flarum.stat.exists
- name: add flarum-{{instance}} init script
  template: dest=/etc/init.d/flarum-{{instance}} src=rc.sh mode=0755
  notify:
  - restart flarum
- name: enable flarum-{{instance}} service
  service: name=flarum-{{instance}} state=started enabled=yes
- import_role: name=nginx-site
