---
  # force eager expansion of variables so that nginx-site below uses exactly what we want
- name: determine path to nginx site template
  set_fact:
    nginx_conf={{role_path}}/templates/nginx.conf
    webroot={{webroot}} # or nginx-site's default will override ours
- import_role: name=nginx-site
- import_tasks: app.yml
