version: 1

global:
  server_name: {{server}}
  private_key: matrix.pem
  key_validity_period: 168h0m0s
  disable_federation: false
  trusted_third_party_id_servers:
  - matrix.org
  - vector.im
  kafka:
    use_naffka: true
    naffka_database:
      connection_string: postgresql:///dendrite?host=/var/run/postgresql
  metrics:
    enabled: false
  sentry:
    enabled: false
  dns_cache:
    enabled: false

tracing:
  enabled: false

logging:
- type: file
  level: info
  params:
    path: /var/log/dendrite

room_server:
  internal_api:
    listen: http://localhost:7770
    connect: http://localhost:7770
  database:
    connection_string: postgresql:///dendrite?host=/var/run/postgresql

client_api:
  internal_api:
    listen: http://localhost:7771
    connect: http://localhost:7771
  registration_disabled: {{ "true" if dendrite.registration_secret is defined else "false" }}
  registration_shared_secret: "{{ dendrite.registration_secret }}"
  rate_limiting:
    enabled: true
    threshold: 5
    cooloff_ms: 500

federation_api:
  internal_api:
    listen: http://localhost:7772
    connect: http://localhost:7772

sync_api:
  internal_api:
    listen: http://localhost:7773
    connect: http://localhost:7773
  database:
    connection_string: postgresql:///dendrite?host=/var/run/postgresql
  real_ip_header: "X-Forwarded-For"

media_api:
  internal_api:
    listen: http://localhost:7774
    connect: http://localhost:7774
  database:
    connection_string: postgresql:///dendrite?host=/var/run/postgresql
  base_path: ./media_store
  max_file_size_bytes: 10485760

federation_sender:
  internal_api:
    listen: http://localhost:7775
    connect: http://localhost:7775
  database:
    connection_string: postgresql:///dendrite?host=/var/run/postgresql
  send_max_retries: 16

app_service_api:
  internal_api:
    listen: http://localhost:7777
    connect: http://localhost:7777
  database:
    connection_string: postgresql:///dendrite?host=/var/run/postgresql
  config_files: []

edu_server:
  internal_api:
    listen: http://localhost:7778
    connect: http://localhost:7778

key_server:
  internal_api:
    listen: http://localhost:7779
    connect: http://localhost:7779
  database:
    connection_string: postgresql:///dendrite?host=/var/run/postgresql

signing_key_server:
  internal_api:
    listen: http://localhost:7780
    connect: http://localhost:7780
  database:
    connection_string: postgresql:///dendrite?host=/var/run/postgresql
  key_perspectives:
  - server_name: matrix.org
    keys:
    - key_id: ed25519:auto
      public_key: Noi6WqcDj0QmPxCNQqgezwTlBKrfqehY1u2FyWP9uYw
    - key_id: ed25519:a_RXGa
      public_key: l8Hft5qXKn1vfHrg3p4+W8gELQVo8N13JkluMfmn2sQ
  prefer_direct_fetch: false

user_api:
  internal_api:
    listen: http://localhost:7781
    connect: http://localhost:7781
  account_database:
    connection_string: postgresql:///dendrite?host=/var/run/postgresql
  device_database:
    connection_string: postgresql:///dendrite?host=/var/run/postgresql
  bcrypt_cost: 10

mscs:
  database:
    connection_string: postgresql:///dendrite?host=/var/run/postgresql
  mscs: []
